**Remark:** In this notebook we will show how to use LLMs to annotate a drug wrt "Level 1 Reactome pathways". Since we're just using putative targets and MOA as strings we are not actually restricted to using drugs from GDSC and PRISM. I.e.: this notebook can be used to <ins>**annotate any drug**</ins>

# 0. Libraries import

Import all necessary libraries and set up the environment. This includes:
- Standard data manipulation libraries (pandas, numpy)
- File system and path management (os, sys, pathlib)
- The vLLM library for efficient large language model inference

In [2]:
# !pip install huggingface_hub

In [2]:
import os
import pandas as pd
import numpy as np
import sys
from pathlib import Path

from vllm import LLM, SamplingParams

/villa/rhh25/Cellhit/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-04-06 15:28:25,569	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

We'll also set the current working directory and define important file paths.

In [3]:
#set current working directory to the library path
library_path = Path('/villa/rhh25/Cellhit/') #replace with yours
os.chdir(library_path)
#sys.path.append(library_path) use this in case it is still not working

We are then ready to import dedicatd fucntions from the custom library

In [4]:
from CellHit.LLMs import fetch_abstracts, generate_prompt
from CellHit.data import obtain_drugs_metadata

In [5]:
#specify the data_path
data_path = library_path/'data'
describe_prompt_path = data_path/'prompts'/'drug_description_prompt.txt'
refine_prompt_path = data_path/'prompts'/'drug_refiner_prompt.txt'
model_path = Path('~/Cellhit/mixtral/').expanduser() # note that the model needs to be downloaded from huggingface, the one used can be found at https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ (gptq-4bit-32g-actorder_True)

In [6]:
model_path

PosixPath('/villa/rhh25/Cellhit/mixtral')

# 1. Getting a drug abstracts

Taking advantage of the custom functions provided in cellHit we can get metadata related to the two dataset used in the manuscript (i.e.: gdsc and prism)

In [6]:
dataset = 'gdsc'
metadata = obtain_drugs_metadata(dataset,data_path)
metadata.head()

,DrugID,Drug,PUTATIVE_TARGET,MOA,DRUG_SYNONYMS,SMILES,repurposing_target
0,1003,Camptothecin,TOP1,DNA replication,"Camptothecine, (+)-Camptothecin",CC[C@@]1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=...,TOP1
1,1004,Vinblastine,Microtubule destabiliser,Mitosis,Velban,CC[C@@]1(C[C@H]2C[C@@](C3=C(CCN(C2)C1)C4=CC=CC...,TUBB
2,1005,Cisplatin,DNA crosslinker,DNA replication,"cis-Diammineplatinum(II) dichloride, Platinol,...",N.N.Cl[Pt]Cl,DNA
3,1006,Cytarabine,Antimetabolite,Other,"Ara-Cytidine, Arabinosyl Cytosine, U-19920",C1=CN(C(=O)N=C1N)[C@H]2[C@H]([C@@H]([C@H](O2)C...,DNA synthesis
4,1007,Docetaxel,Microtubule stabiliser,Mitosis,"RP-56976, Taxotere",CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@]([C@...,TUBB

After having selected the drug of interest we can fix its name

In [7]:
drug_name = 'Docetaxel'

and afterwards extraxt known metadata realted to this drug such as putative targets and mechanism of action

In [8]:
metadata.loc[metadata['Drug']==drug_name]

,DrugID,Drug,PUTATIVE_TARGET,MOA,DRUG_SYNONYMS,SMILES,repurposing_target
4,1007,Docetaxel,Microtubule stabiliser,Mitosis,"RP-56976, Taxotere",CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@]([C@...,TUBB

In [9]:
mechanism_of_action = metadata.loc[metadata['Drug']==drug_name]['MOA'].values[0]
putative_target = metadata.loc[metadata['Drug']==drug_name]['repurposing_target'].values[0]
mechanism_of_action,putative_target

('Mitosis', 'TUBB')

In [10]:
drug_name

'Docetaxel'

We then use the  `fetch_abstracts` function to get the abstracts related to the selected drug

In [11]:
abstracts = fetch_abstracts(drug_name,mail=None,k=10)
abstracts = [str(a) for a in abstracts]
abstracts

/villa/rhh25/Cellhit/venv/lib/python3.10/site-packages/Bio/Entrez/__init__.py:694: UserWarning:
            Email address is not specified.

            To make use of NCBI's E-utilities, NCBI requires you to specify your
            email address with each request.  As an example, if your email address
            is A.N.Other@example.com, you can specify it as follows:
               from Bio import Entrez
               Entrez.email = 'A.N.Other@example.com'
            In case of excessive usage of the E-utilities, NCBI will attempt to contact
            a user at the email address provided before blocking access to the
            E-utilities.
  warnings.warn(

Abstract 9 is not available.

['<b>Background:</b> Prostate cancer is usually considered as immune "cold" tumor with poor immunogenic response and low density of tumor-infiltrating immune cells, highlighting the need to explore clinically actionable strategies to sensitize prostate cancer to immunotherapy. In this study, we investigated whether docetaxel-based chemohormonal therapy induces immunologic changes and potentiates checkpoint blockade immunotherapy in prostate cancer. <b>Methods:</b> We performed transcriptome and histopathology analysis to characterize the changes of prostate cancer immune microenvironment before and after docetaxel-based chemohormonal therapy. Furthermore, we investigated the therapeutic benefits and underlying mechanisms of chemohormonal therapy combined with anti-PD1 blockade using cellular experiments and xenograft prostate cancer models. Finally, we performed a retrospective cohort analysis to evaluate the antitumor efficacy of anti-PD1 blockade alone or in combination with docetaxel-based chemotherapy. <b>Results:</b> Histopathology assessments on patient samples confirmed the enrichment of tumor-infiltrating T cells after chemohormonal therapy. Moreover, we found that docetaxel activated the cGAS/STING pathway in prostate cancer, subsequently induced IFN signaling, resulting in lymphocytes infiltration. In a xenograft mouse model, docetaxel-based chemohormonal therapy prompted the intratumoral infiltration of T cells and upregulated the abundance of PD1 and PD-L1, thereby sensitizing mouse tumors to the anti-PD1 blockade. To determine the clinical significance of these results, we retrospectively analyzed a cohort of 30 metastatic castration-resistant prostate cancer patients and found that docetaxel combined with anti-PD1 blockade resulted in better prostate-specific antigen progression-free survival when compared with anti-PD1 blockade alone. <b>Conclusions:</b> Our study demonstrates that docetaxel activates the antitumoral immune response and facilitates T cell infiltration in a cGAS/STING-dependent manner, providing a combination immunotherapy strategy that would improve the clinical benefits of immunotherapy.',
 'We reviewed the preclinical and clinical profiles of the antineoplastic taxoid docetaxel (Taxotere, Rhône-Poulenc Rorer, Collegeville, PA).',
 'Cuproptosis, a newly discovered programmed cell death induced by copper ions, is associated with the progression and drug resistance of various tumors. Docetaxel plays a vital role as a first-line chemotherapeutic agent for advanced prostate cancer; however, most patients end up with prostate cancer progression because of inherent or acquired resistance. Herein, we examined the role of cuproptosis in the chemotherapeutic resistance of prostate cancer to docetaxel. We treated prostate cancer cell lines with elesclomol-CuCl<sub>2</sub> , as well as with docetaxel. We performed analyses of CCK8, colony formation tests, cell cycle flow assay, transmission electron microscopy, and mTOR signaling in treated cells, and treated a xenograft prostate cancer model with elesclomol-CuCl<sub>2</sub> and docetaxel in vivo, and performed immunohistochemistry and Western blotting analysis in treated tumors. We found that elesclomol-CuCl<sub>2</sub> could promote cell death and enhance chemosensitivity to docetaxel. Elesclomol-CuCl<sub>2</sub> induced cell death and inhibited the growth of prostate cancer cells relying on copper ions-induced cuproptosis, not elesclomol. In addition, dihydrolipoamide S-acetyltransferase (DLAT) was involved in cuproptosis-enhanced drug sensitivity to docetaxel. Mechanistically, upregulated DLAT by cuproptosis inhibited autophagy, promoted G2/M phase retention of cells, and enhanced the sensitivity to docetaxel chemotherapy in vitro and in vivo via the mTOR signaling pathway. Our findings demonstrated that the cuproptosis-regulated DLAT/mTOR pathway inhibited autophagy and promoted cells in G2/M phase retention, thus enhancing the chemosensitivity to docetaxel. This discovery may provide an effective therapeutic option for treating advanced prostate cancer by inhibiting the chemotherapeutic resistance to docetaxel.',
 'The recent identification of the cell-surface protein DSC1 (desmocollin 1) as a negative regulator of HDL (high-density lipoprotein) biogenesis has attracted us to revisit the old HDL biogenesis hypothesis: HDL biogenesis reduces atherosclerosis. The location and function of DSC1 suggest that DSC1 is a druggable target for the promotion of HDL biogenesis, and the discovery of docetaxel as a potent inhibitor of the DSC1 sequestration of apolipoprotein A-I has provided us with new opportunities to test this hypothesis. The FDA-approved chemotherapy drug docetaxel promotes HDL biogenesis at low-nanomolar concentrations that are far lower than used in chemotherapy. Docetaxel has also been shown to inhibit atherogenic proliferation of vascular smooth muscle cells. In accordance with these atheroprotective effects of docetaxel, animal studies have shown that docetaxel reduces dyslipidemia-induced atherosclerosis. In the absence of HDL-directed therapies for atherosclerosis, DSC1 constitutes an important new target for the promotion of HDL biogenesis, and the DSC1-targeting compound docetaxel serves as a model compound to prove the hypothesis. In this brief review, we discuss opportunities, challenges, and future directions for using docetaxel in the prevention and treatment of atherosclerosis.',
 'There are several interactions within the tumor microenvironment (TME) that affect the response of cancer cells to therapy. There are also a large number of cells and secretions in TME that increase resistance to therapy. Following the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, immune evasion, angiogenesis, and metastasis may be induced. However, natural killer (NK) cells and cytotoxic CD8\xa0+\xa0T lymphocytes (CTLs) can responsively release anticancer molecules. In addition, anticancer drugs can modulate these cells and their interactions in favor of either cancer resistance or therapy. Docetaxel belongs to taxanes, a class of anti-tumor drugs, which acts through the polymerization of tubulin and the induction of cell cycle arrest. Also, it has been revealed that taxanes including docetaxel affect cancer cells and the other cells within TME through some other mechanisms such as modulation of immune system responses, angiogenesis, and metastasis. In this paper, we explain the basic mechanisms of docetaxel interactions with malignant cells. Besides, we review the diverse effects of docetaxel on TME and cancer cells in consequence. Lastly, the modulatory effects of docetaxel alone or in conjunction with other anticancer agents on anti-tumor immunity, cancer cell resistance, angiogenesis, and metastasis will be discussed.',
 'Flagellate erythema is a distinctive morphologic reaction pattern recognized by whiplash-like pruritic erythematous eruption. It is usually encountered in patients receiving bleomycin. Only one case of docetaxel-induced flagellate erythema is reported in the literature.',
 'Recent years have witnessed a huge shift in the management and prognosis of metastatic prostate cancer with the advent of new-generation anti-hormonal treatments. Docetaxel, which was initially approved in the castrate-resistant prostate cancer setting, has been approved in the earlier course of the disease as it is still castrate sensitive.',
 'Docetaxel has had a significant impact on the management of urothelial carcinoma (UC). Multiple phase II trials have been conducted to evaluate the efficacy of docetaxel in the treatment of metastatic UC. Docetaxel is an accepted community standard for the therapy of platinum-treated patients with metastatic UC.',
 'Docetaxel has exhibited substantial clinical activity against platinum, refrac- tory, paclitaxel resistant and previously untreated advanced ovarian cancer. As single agent, in advanced ovarian cancer patients previously treated with platinum agents, docetaxel 100 mg/m(2) every 3 weeks yields a 30% overall response rate and 6 months duration of response. In vitro data demonstrate a lack of complete cross-resistance bet- ween docetaxel and paclitaxel. In both platinum- and paclitaxel-pretreated patients, the highest response rates were obtained in patients with the longest interval of time since receipt of prior chemotherapy. Docetaxel currently is being intensively evaluated as a component of first line combination chemotherapy for ovarian cancer. Phase I-II have shown that docetaxel-platinum doublets are feasible and highly effective in the treatment of ovarian cancer, with docetaxel-carboplatin providing a more favorable safety profile compared with docetaxel-cisplatin, particularly with respect to neurotoxicity. The preliminary results of a phase III comparison of docetaxel-carboplatin versus paclitaxel-carboplatin support the clinical use of docetaxel-carboplatin as first line chemotherapy for stage IC to IV ovarian cancer, as it was shown to reduce the incidence of grade > 2 neurosensory toxicity compared to paclitaxel-carboplatin. Comparative overall survival and quality of life and more mature progression free survival data will be instrumental in determining the relative merits of docetaxel-carboplatin and paclitaxel-carboplatin as first line adjuvant therapy for ovarian cancer. The positive clinical experiences with docetaxel-provide a strong basis for continued investigation of docetaxel-carboplatin-based chemotherapy as component of advanced ovarian cancer management.']

# 2. Generating a drug description

We now make us of the VLLM library to do serve the LLM

In [12]:
ls

AsyncDistribJobs/      mixtral/
CellHit/               notebooks/
cellHit.yml            NOTICE
data/                  protein.physical.links.v12.0.txt.gz
drugcomb_moa_data.csv  README.md
get-pip.py             requirements.txt
hfd.sh*                scripts/
learning_workflow.png  venv/
LICENSE

In [13]:
str(model_path)

'/villa/rhh25/Cellhit/mixtral'

In [14]:
!pip install "huggingface_hub==0.20.3"

Requirement already satisfied: huggingface_hub==0.20.3 in ./venv/lib/python3.10/site-packages (0.20.3)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from huggingface_hub==0.20.3) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in ./venv/lib/python3.10/site-packages (from huggingface_hub==0.20.3) (2024.2.0)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from huggingface_hub==0.20.3) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in ./venv/lib/python3.10/site-packages (from huggingface_hub==0.20.3) (4.66.2)
Requirement already satisfied: pyyaml>=5.1 in ./venv/lib/python3.10/site-packages (from huggingface_hub==0.20.3) (6.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./venv/lib/python3.10/site-packages (from huggingface_hub==0.20.3) (4.15.0)
Requirement already satisfied: packaging>=20.9 in ./venv/lib/python3.10/site-packages (from huggingface_hub==0.20.3) (24.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests->huggingface_hub==0.20.3) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->huggingface_hub==0.20.3) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->huggingface_hub==0.20.3) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->huggingface_hub==0.20.3) (2022.12.7)

In [15]:
llm = LLM(
            model=str(model_path),
            revision="gptq-4bit-32g-actorder_True",
            quantization="gptq",
            dtype='float16',
            gpu_memory_utilization=1,
            enforce_eager=True)
            #**{"attn_implementation":"flash_attention_2"}) Turn on for faster decoding (Ampere and newer GPUs only)

#initialize sampling parameters
sampling_params = SamplingParams(temperature=0.2, top_p=0.95, max_tokens=1024)

WARNING 04-02 17:30:05 config.py:618] Casting torch.bfloat16 to torch.float16.
WARNING 04-02 17:30:05 config.py:193] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 04-02 17:30:05 llm_engine.py:87] Initializing an LLM engine with config: model='/villa/rhh25/Cellhit/mixtral', tokenizer='/villa/rhh25/Cellhit/mixtral', tokenizer_mode=auto, revision=gptq-4bit-32g-actorder_True, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)

INFO 04-02 17:35:29 llm_engine.py:357] # GPU blocks: 6472, # CPU blocks: 2048

We generate the prompt using a dedicated function that takes care of inserting into a template the informations recovered about the selected drug

In [16]:
describe_prompt = generate_prompt(describe_prompt_path,**{'drug_name':drug_name, 'mechanism_of_action':mechanism_of_action, 'putative_targets':putative_target})
print(describe_prompt)

<|im_start|>system
**Task**: Utilizing the drug metadata that i provide you with, act as a medicinal chemist and expert molecular biologist to generate an in-depth description of the drug.

**Instructions**:
1. Analyze the provided drug metadata, including its name, synthetic labels of the mechanism of action, and putative targets.
2. Generate a detailed textual description of the drug's mechanism of action. This should include how the drug interacts with biological systems, its effect on specific cellular or molecular targets, and its overall impact on the disease or condition it is designed to treat.
3. If available, provide a detailed textual description of the drug's metabolism. This includes how the drug is metabolized in the body, the enzymes involved, the metabolic pathways, and any known metabolites formed.
4. Ensure that the information is presented in a clear, concise, and scientifically accurate manner, suitable for an audience with a background in medicinal chemistry and molecular biology.
5. Try not to exceed 350 words in your description.

**Output Format**:
1. **Mechanism of Action Description**:
   - [Detailed description of the drug's mechanism of action, covering its interaction with biological systems, effects on cellular or molecular targets, and overall impact on the intended disease or condition.]

2. **Metabolism Description**:
   - [If available known, a detailed description of the drug's metabolism, including metabolic pathways, enzymes involved, and known metabolites.]<|im_end|>
<|im_start|>user
**Drug Metadata**
- Drug Name: Docetaxel
- Synthetic Labels of Mechanism of Action: Mitosis
- Putative Targets: TUBB<|im_end|>
<|im_start|>assistant

We can than query the LLM and obtain its answer

In [20]:
sampling_params

SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.2, top_p=0.95, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True)

In [27]:
outputs = llm.generate(describe_prompt, sampling_params)

Processed prompts: 100%|██████████| 1/1 [00:23<00:00, 23.70s/it]

In [28]:
drug_description = outputs[0].outputs[0].text
print(drug_description)

**Mechanism of Action Description**

Docetaxel is a semi-synthetic derivative of the natural compound paclitaxel, which is isolated from the bark of the Pacific yew tree (Taxus brevifolia). Docetaxel is a potent antineoplastic agent that exerts its effects by interfering with microtubule dynamics during mitosis, leading to cell cycle arrest and ultimately, apoptosis.

Docetaxel binds to the beta subunit of tubulin, a protein responsible for the polymerization and stabilization of microtubules. This interaction stabilizes microtubules, preventing their disassembly during mitosis. Consequently, this results in the inhibition of mitotic spindle formation, chromosomal separation, and ultimately, cell division. The accumulation of cells in the G2-M phase of the cell cycle triggers the onset of apoptosis, leading to the death of cancer cells.

**Metabolism Description**

Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 (CYP) enzyme system, primarily by CYP3A4. The major metabolic pathways involve N-dealkylation, hydroxylation, and oxidation. The primary metabolite of docetaxel is 6α-hydroxy-docetaxel, which retains some antineoplastic activity but is significantly less potent than the parent compound.

The metabolism of docetaxel is influenced by several factors, including hepatic function, concomitant medications, and genetic polymorphisms in the CYP3A4 enzyme. Docetaxel has a high affinity for P-glycoprotein, an efflux transporter responsible for limiting drug accumulation in cancer cells. This interaction can further influence the drug's pharmacokinetics and pharmacodynamics, leading to potential drug-drug interactions and variable clinical responses.

In summary, docetaxel is a potent antineoplastic agent that exerts its effects by interfering with microtubule dynamics during mitosis, leading to cell cycle arrest and apoptosis. The drug undergoes extensive metabolism in the liver by the CYP3A4 enzyme system, primarily through N-dealkylation, hydroxylation, and oxidation. The major metabolite of docetaxel is 6α-hydroxy-docetaxel, which retains some antineoplastic activity but is significantly less potent than the parent compound.

# 3.Refine the drug description with abstracts

We now repeat the procedure above but this time integrating the infos generated at the previous step and integrating them with the abstracts

In [29]:
refine_prompt = generate_prompt(refine_prompt_path,**{'previous_output':drug_description,'formatted_abstracts':"\n".join([f"Abstract {i+1}: {abstract}" for i, abstract in enumerate(abstracts)])})
print(refine_prompt)

<|im_start|>system
**Task**: Review and integrate a drug summary using the provided PubMed abstracts related to the drug. Synthesize both sets of information, offering corrections and updates as necessary.

**Instructions**:
1. Carefully read the output from the previous instruction, which contains a detailed description of the drug's mechanism of action and metabolism.
2. Review the list of PubMed abstracts, disregarding any information that is not relevant to the drug and focusing on key information that pertains to the drug's mechanism of action, metabolism, and any other relevant pharmacological details.
3. Compare and contrast the information from the previous output and the PubMed abstracts. Identify any discrepancies or conflicts between the two sources.
4. In case of conflicting information, give precedence to the information contained in the PubMed abstracts, as they are based on recent scientific research and publications.
5. Integrate the verified information and the new insights from the abstracts to create an updated, accurate summary of the drug's properties and effects.
6. Don't add references to the abstracts, but rather integrate the information into the summary.
7. Ensure that the summary is clear, concise, and scientifically accurate, suitable for an audience with a background in medicinal chemistry and molecular biology.
8. Try not to exceed 500 words in your description.

**Output Format**:
1. **Mechanism of Action Description**:
  - [Integrated and possibly corrected description of the drug's mechanism of action, considering both the previous output and the PubMed abstracts.]

2. **Metabolism Description**:
  - [If known, an integrated and possibly corrected description of the drug's metabolism, considering both the previous output and the PubMed abstracts.]

3. **Additional Relevant Information**:
  - [If any, other relevant pharmacological details or insights derived from the PubMed abstracts.]<|im_end|>
<|im_start|>user
**[Start of drug summary]**

**Mechanism of Action Description**

Docetaxel is a semi-synthetic derivative of the natural compound paclitaxel, which is isolated from the bark of the Pacific yew tree (Taxus brevifolia). Docetaxel is a potent antineoplastic agent that exerts its effects by interfering with microtubule dynamics during mitosis, leading to cell cycle arrest and ultimately, apoptosis.

Docetaxel binds to the beta subunit of tubulin, a protein responsible for the polymerization and stabilization of microtubules. This interaction stabilizes microtubules, preventing their disassembly during mitosis. Consequently, this results in the inhibition of mitotic spindle formation, chromosomal separation, and ultimately, cell division. The accumulation of cells in the G2-M phase of the cell cycle triggers the onset of apoptosis, leading to the death of cancer cells.

**Metabolism Description**

Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 (CYP) enzyme system, primarily by CYP3A4. The major metabolic pathways involve N-dealkylation, hydroxylation, and oxidation. The primary metabolite of docetaxel is 6α-hydroxy-docetaxel, which retains some antineoplastic activity but is significantly less potent than the parent compound.

The metabolism of docetaxel is influenced by several factors, including hepatic function, concomitant medications, and genetic polymorphisms in the CYP3A4 enzyme. Docetaxel has a high affinity for P-glycoprotein, an efflux transporter responsible for limiting drug accumulation in cancer cells. This interaction can further influence the drug's pharmacokinetics and pharmacodynamics, leading to potential drug-drug interactions and variable clinical responses.

In summary, docetaxel is a potent antineoplastic agent that exerts its effects by interfering with microtubule dynamics during mitosis, leading to cell cycle arrest and apoptosis. The drug undergoes extensive metabolism in the liver by the CYP3A4 enzyme system, primarily through N-dealkylation, hydroxylation, and oxidation. The major metabolite of docetaxel is 6α-hydroxy-docetaxel, which retains some antineoplastic activity but is significantly less potent than the parent compound.
**[End of drug summary]**

**[Start of PubMed Abstracts]**
Abstract 1: <b>Background:</b> Prostate cancer is usually considered as immune "cold" tumor with poor immunogenic response and low density of tumor-infiltrating immune cells, highlighting the need to explore clinically actionable strategies to sensitize prostate cancer to immunotherapy. In this study, we investigated whether docetaxel-based chemohormonal therapy induces immunologic changes and potentiates checkpoint blockade immunotherapy in prostate cancer. <b>Methods:</b> We performed transcriptome and histopathology analysis to characterize the changes of prostate cancer immune microenvironment before and after docetaxel-based chemohormonal therapy. Furthermore, we investigated the therapeutic benefits and underlying mechanisms of chemohormonal therapy combined with anti-PD1 blockade using cellular experiments and xenograft prostate cancer models. Finally, we performed a retrospective cohort analysis to evaluate the antitumor efficacy of anti-PD1 blockade alone or in combination with docetaxel-based chemotherapy. <b>Results:</b> Histopathology assessments on patient samples confirmed the enrichment of tumor-infiltrating T cells after chemohormonal therapy. Moreover, we found that docetaxel activated the cGAS/STING pathway in prostate cancer, subsequently induced IFN signaling, resulting in lymphocytes infiltration. In a xenograft mouse model, docetaxel-based chemohormonal therapy prompted the intratumoral infiltration of T cells and upregulated the abundance of PD1 and PD-L1, thereby sensitizing mouse tumors to the anti-PD1 blockade. To determine the clinical significance of these results, we retrospectively analyzed a cohort of 30 metastatic castration-resistant prostate cancer patients and found that docetaxel combined with anti-PD1 blockade resulted in better prostate-specific antigen progression-free survival when compared with anti-PD1 blockade alone. <b>Conclusions:</b> Our study demonstrates that docetaxel activates the antitumoral immune response and facilitates T cell infiltration in a cGAS/STING-dependent manner, providing a combination immunotherapy strategy that would improve the clinical benefits of immunotherapy.
Abstract 2: We reviewed the preclinical and clinical profiles of the antineoplastic taxoid docetaxel (Taxotere, Rhône-Poulenc Rorer, Collegeville, PA).
Abstract 3: Cuproptosis, a newly discovered programmed cell death induced by copper ions, is associated with the progression and drug resistance of various tumors. Docetaxel plays a vital role as a first-line chemotherapeutic agent for advanced prostate cancer; however, most patients end up with prostate cancer progression because of inherent or acquired resistance. Herein, we examined the role of cuproptosis in the chemotherapeutic resistance of prostate cancer to docetaxel. We treated prostate cancer cell lines with elesclomol-CuCl<sub>2</sub> , as well as with docetaxel. We performed analyses of CCK8, colony formation tests, cell cycle flow assay, transmission electron microscopy, and mTOR signaling in treated cells, and treated a xenograft prostate cancer model with elesclomol-CuCl<sub>2</sub> and docetaxel in vivo, and performed immunohistochemistry and Western blotting analysis in treated tumors. We found that elesclomol-CuCl<sub>2</sub> could promote cell death and enhance chemosensitivity to docetaxel. Elesclomol-CuCl<sub>2</sub> induced cell death and inhibited the growth of prostate cancer cells relying on copper ions-induced cuproptosis, not elesclomol. In addition, dihydrolipoamide S-acetyltransferase (DLAT) was involved in cuproptosis-enhanced drug sensitivity to docetaxel. Mechanistically, upregulated DLAT by cuproptosis inhibited autophagy, promoted G2/M phase retention of cells, and enhanced the sensitivity to docetaxel chemotherapy in vitro and in vivo via the mTOR signaling pathway. Our findings demonstrated that the cuproptosis-regulated DLAT/mTOR pathway inhibited autophagy and promoted cells in G2/M phase retention, thus enhancing the chemosensitivity to docetaxel. This discovery may provide an effective therapeutic option for treating advanced prostate cancer by inhibiting the chemotherapeutic resistance to docetaxel.
Abstract 4: The recent identification of the cell-surface protein DSC1 (desmocollin 1) as a negative regulator of HDL (high-density lipoprotein) biogenesis has attracted us to revisit the old HDL biogenesis hypothesis: HDL biogenesis reduces atherosclerosis. The location and function of DSC1 suggest that DSC1 is a druggable target for the promotion of HDL biogenesis, and the discovery of docetaxel as a potent inhibitor of the DSC1 sequestration of apolipoprotein A-I has provided us with new opportunities to test this hypothesis. The FDA-approved chemotherapy drug docetaxel promotes HDL biogenesis at low-nanomolar concentrations that are far lower than used in chemotherapy. Docetaxel has also been shown to inhibit atherogenic proliferation of vascular smooth muscle cells. In accordance with these atheroprotective effects of docetaxel, animal studies have shown that docetaxel reduces dyslipidemia-induced atherosclerosis. In the absence of HDL-directed therapies for atherosclerosis, DSC1 constitutes an important new target for the promotion of HDL biogenesis, and the DSC1-targeting compound docetaxel serves as a model compound to prove the hypothesis. In this brief review, we discuss opportunities, challenges, and future directions for using docetaxel in the prevention and treatment of atherosclerosis.
Abstract 5: There are several interactions within the tumor microenvironment (TME) that affect the response of cancer cells to therapy. There are also a large number of cells and secretions in TME that increase resistance to therapy. Following the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, immune evasion, angiogenesis, and metastasis may be induced. However, natural killer (NK) cells and cytotoxic CD8 + T lymphocytes (CTLs) can responsively release anticancer molecules. In addition, anticancer drugs can modulate these cells and their interactions in favor of either cancer resistance or therapy. Docetaxel belongs to taxanes, a class of anti-tumor drugs, which acts through the polymerization of tubulin and the induction of cell cycle arrest. Also, it has been revealed that taxanes including docetaxel affect cancer cells and the other cells within TME through some other mechanisms such as modulation of immune system responses, angiogenesis, and metastasis. In this paper, we explain the basic mechanisms of docetaxel interactions with malignant cells. Besides, we review the diverse effects of docetaxel on TME and cancer cells in consequence. Lastly, the modulatory effects of docetaxel alone or in conjunction with other anticancer agents on anti-tumor immunity, cancer cell resistance, angiogenesis, and metastasis will be discussed.
Abstract 6: Flagellate erythema is a distinctive morphologic reaction pattern recognized by whiplash-like pruritic erythematous eruption. It is usually encountered in patients receiving bleomycin. Only one case of docetaxel-induced flagellate erythema is reported in the literature.
Abstract 7: Recent years have witnessed a huge shift in the management and prognosis of metastatic prostate cancer with the advent of new-generation anti-hormonal treatments. Docetaxel, which was initially approved in the castrate-resistant prostate cancer setting, has been approved in the earlier course of the disease as it is still castrate sensitive.
Abstract 8: Docetaxel has had a significant impact on the management of urothelial carcinoma (UC). Multiple phase II trials have been conducted to evaluate the efficacy of docetaxel in the treatment of metastatic UC. Docetaxel is an accepted community standard for the therapy of platinum-treated patients with metastatic UC.
Abstract 9: Docetaxel has exhibited substantial clinical activity against platinum, refrac- tory, paclitaxel resistant and previously untreated advanced ovarian cancer. As single agent, in advanced ovarian cancer patients previously treated with platinum agents, docetaxel 100 mg/m(2) every 3 weeks yields a 30% overall response rate and 6 months duration of response. In vitro data demonstrate a lack of complete cross-resistance bet- ween docetaxel and paclitaxel. In both platinum- and paclitaxel-pretreated patients, the highest response rates were obtained in patients with the longest interval of time since receipt of prior chemotherapy. Docetaxel currently is being intensively evaluated as a component of first line combination chemotherapy for ovarian cancer. Phase I-II have shown that docetaxel-platinum doublets are feasible and highly effective in the treatment of ovarian cancer, with docetaxel-carboplatin providing a more favorable safety profile compared with docetaxel-cisplatin, particularly with respect to neurotoxicity. The preliminary results of a phase III comparison of docetaxel-carboplatin versus paclitaxel-carboplatin support the clinical use of docetaxel-carboplatin as first line chemotherapy for stage IC to IV ovarian cancer, as it was shown to reduce the incidence of grade > 2 neurosensory toxicity compared to paclitaxel-carboplatin. Comparative overall survival and quality of life and more mature progression free survival data will be instrumental in determining the relative merits of docetaxel-carboplatin and paclitaxel-carboplatin as first line adjuvant therapy for ovarian cancer. The positive clinical experiences with docetaxel-provide a strong basis for continued investigation of docetaxel-carboplatin-based chemotherapy as component of advanced ovarian cancer management.
**[End of PubMed Abstracts]**<|im_end|>
<|im_start|>assistant

In [30]:
outputs = llm.generate(refine_prompt, sampling_params)

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts: 100%|██████████| 1/1 [00:44<00:00, 44.39s/it]

In [31]:
refined_drug_description = outputs[0].outputs[0].text
print(refined_drug_description)

**Mechanism of Action Description**

Docetaxel is a semi-synthetic derivative of paclitaxel, a compound isolated from the Pacific yew tree. It is a potent antineoplastic agent that exerts its effects by interfering with microtubule dynamics during mitosis, leading to cell cycle arrest and ultimately, apoptosis. Docetaxel binds to the beta subunit of tubulin, a protein responsible for the polymerization and stabilization of microtubules. This interaction stabilizes microtubules, preventing their disassembly during mitosis, which results in the inhibition of mitotic spindle formation, chromosomal separation, and ultimately, cell division. The accumulation of cells in the G2-M phase of the cell cycle triggers the onset of apoptosis, leading to the death of cancer cells.

In addition to its direct effects on microtubules, docetaxel has been found to activate the cGAS/STING pathway in prostate cancer, subsequently inducing IFN signaling and resulting in lymphocytes infiltration. This immunomodulatory effect can potentially sensitize prostate cancer to checkpoint blockade immunotherapy.

**Metabolism Description**

Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 (CYP) enzyme system, primarily by CYP3A4. The major metabolic pathways involve N-dealkylation, hydroxylation, and oxidation. The primary metabolite of docetaxel is 6α-hydroxy-docetaxel, which retains some antineoplastic activity but is significantly less potent than the parent compound.

The metabolism of docetaxel is influenced by several factors, including hepatic function, concomitant medications, and genetic polymorphisms in the CYP3A4 enzyme. Docetaxel has a high affinity for P-glycoprotein, an efflux transporter responsible for limiting drug accumulation in cancer cells. This interaction can further influence the drug's pharmacokinetics and pharmacodynamics, leading to potential drug-drug interactions and variable clinical responses.

**Additional Relevant Information**

Docetaxel has been found to modulate the tumor microenvironment, activating the cGAS/STING pathway and inducing IFN signaling, leading to lymphocytes infiltration. This effect can potentially sensitize prostate cancer to checkpoint blockade immunotherapy.

In addition to its antineoplastic effects, docetaxel has been found to promote HDL biogenesis at low-nanomolar concentrations that are far lower than used in chemotherapy. This effect could potentially provide atheroprotective benefits in the context of atherosclerosis.

Docetaxel has also been found to affect cancer cells and the other cells within the tumor microenvironment (TME) through some other mechanisms such as modulation of immune system responses, angiogenesis, and metastasis. For example, docetaxel has been found to modulate immune system responses, affecting cancer cells and the other cells within TME.

Mechanisms of docetaxel interactions with malignant cells include polymerization of tubulin and induction of cell cycle arrest. However, docetaxel also affects cancer cells and the other cells within TME through some other mechanisms such as modulation of immune system responses, angiogenesis, and metastasis. The modulatory effects of docetaxel alone or in conjunction with other anticancer agents on anti-tumor immunity, cancer cell resistance, angiogenesis, and metastasis will be discussed.

In summary, docetaxel is a potent antineoplastic agent that exerts its effects by interfering with microtubule dynamics during mitosis, leading to cell cycle arrest and apoptosis. The drug undergoes extensive metabolism in the liver by the CYP3A4 enzyme system, primarily through N-dealkylation, hydroxylation, and oxidation. The major metabolite of docetaxel is 6α-hydroxy-docetaxel, which retains some antineoplastic activity but is significantly less potent than the parent compound. In addition to its direct effects on microtubules, docetaxel has been found to activate the cGAS/STING pathway in prostate cancer, inducing IFN signaling and resulting in lymphocytes infil

In [32]:
#dump refined_drug_description to a file
with open('drug_description_refined.txt','w') as f:
    f.write(refined_drug_description)

# 4. Pathway selection

In this part of the notebook we serve the LLM model with a different library: [Guidance](https://github.com/guidance-ai/guidance). This will let us do constrained inference. 

*It is suggested to restart the notebook before running this new part. We are currently working to obtain a new version of the notebook to avoid switching libraries using [SGLang](https://github.com/sgl-project/sglang).*

In [ ]:
import gc
import torch
import guidance
import pandas as pd
from guidance import select,gen,models
from pathlib import Path

from CellHit.data import get_reactome_layers,get_pathway_genes
from CellHit.LLMs import generate_prompt,dictionary_maker,self_consistency

In [8]:
#specify the data_path
select_prompt_path = data_path/'prompts'/'mixtral_pathway_selector.txt'
model_path = Path('~/Cellhit/mixtral/').expanduser()

Using the `get_reactome_layers` from our codebase we can automatically obtain the Reactome pathways at a given level "of depth". For more info about this we refer to the method section of our manuscript

In [9]:
reactome_pathways = get_reactome_layers(data_path/'reactome',layer_number=1)['PathwayName'].tolist()

In [10]:
reactome_pathways[:10]

['ABC-family proteins mediated transport',
 'Abacavir ADME',
 'Activation of HOX genes during differentiation',
 'Adaptive Immune System',
 'Amyloid fiber formation',
 'Apoptosis',
 'Aquaporin-mediated transport',
 'Aspirin ADME',
 'Atorvastatin ADME',
 'Azathioprine ADME']

We read the drug description obtained in the previous steps (since we will use it now to associate to the drugs the Reactome pathways)

In [11]:
#read the refined drug description
with open('drug_description_refined.txt','r') as f:
    drug_description = f.read()

We then define the constrained generation logic that we will use in order to associate the pathways to the drug

In [12]:
@guidance
def inference(lm,prompt, pathway_number, pathways_list,temperature=0.7):

    break_line = "\n"

    lm += prompt

    choosen_pathways = []
    #controlled generation
    for i in range(pathway_number):
        feasible_pathways = [i for i in pathways_list if i not in set(choosen_pathways)]
        lm += f"\nRationale {i+1}:{gen(f'rationale_{i+1}',stop=break_line,temperature=temperature)}"
        lm += f"\nPathway {i+1}:{select(options=feasible_pathways,name=f'pathway_{i+1}')}\n"
        choosen_pathways.append(lm[f'pathway_{i+1}'])
    return lm

We then load the model

In [13]:
gpu_id = 0
lm = models.Transformers(str(model_path),**{"device_map":f"cuda:{gpu_id}","revision":"gptq-4bit-32g-actorder_True"})

/villa/rhh25/Cellhit/venv/lib/python3.10/site-packages/transformers/modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(

In [15]:
pathway_number = 15
self_k = 5
temperature = 0.7

In [ ]:
prompt = generate_prompt(data_path/'prompts'/'mixtral_pathway_selector.txt',**{'drug_description':drug_description,'pathways_list':reactome_pathways,'pathway_number':pathway_number})
print(prompt)

**[INST] [Start of Drug Description]**

**Mechanism of Action Description**:
Docetaxel is a semisynthetic antineoplastic agent that exerts its effects by binding to and stabilizing microtubules, thereby inhibiting the dynamics of microtubule disassembly and promoting microtubule polymerization. This interference with microtubule dynamics prevents the formation of the mitotic spindle, which is essential for cell division. Consequently, docetaxel induces cell cycle arrest at the G2/M phase, leading to apoptotic cell death in proliferating cells. The primary target of docetaxel is the beta-tubulin subunit of microtubules, specifically the TUBB protein. Recent studies have also shown that docetaxel can activate the cGAS/STING pathway in prostate cancer, subsequently inducing IFN signaling, resulting in lymphocytes infiltration. This immune response facilitates T cell infiltration in a cGAS/STING-dependent manner, providing a combination immunotherapy strategy that would improve the clinical benefits of immunotherapy.

**Metabolism Description**:
Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 system, primarily by CYP3A4. The major metabolic pathways involve hydroxylation of the side chains and the formation of both glucuronide and sulfate conjugates. The primary metabolites include 6α-hydroxy-docetaxel, 6β-hydroxy-docetaxel, and their respective glucuronide and sulfate conjugates. These metabolites are generally less active than the parent compound, docetaxel. The biliary route is the primary excretion pathway for both the parent drug and its metabolites, with minimal renal excretion observed.

**Additional Relevant Information**:
Docetaxel has been shown to modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. However, it can also increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis. Therefore, the modulatory effects of docetaxel alone or in conjunction with other anticancer agents on anti-tumor immunity, cancer cell resistance, angiogenesis, and metastasis should be carefully considered in its clinical use.

In terms of therapeutic applications, docetaxel has been approved in the earlier course of prostate cancer, as it is still castrate sensitive. It has also been approved in the treatment of metastatic urothelial carcinoma and ovarian cancer, demonstrating substantial clinical activity against platinum, paclitaxel resistant, and previously untreated advanced ovarian cancer. The positive clinical experiences with docetaxel provide a strong basis for continued investigation of docetaxel-based chemotherapy as a component of advanced ovarian cancer management.

Docetaxel can also induce cell death and enhance chemosensitivity to docetaxel in prostate cancer cells by promoting cuproptosis, a copper-induced programmed cell death. This discovery may provide an effective therapeutic option for treating advanced prostate cancer by inhibiting the chemotherapeutic resistance to docetaxel.

Additionally, docetaxel has been shown to promote HDL biogenesis at low-nanomolar concentrations, far lower than used in chemotherapy. This property may provide new opportunities for the prevention and treatment of atherosclerosis, a disease characterized by the dyslipidemia-induced atherosclerosis.

It is important to note that in the absence of HDL-directed therapies for atherosclerosis, DSC1 constitutes an important new target for the promotion of HDL biogenesis, and the DSC1-targeting compound docetaxel serves as a model compound to prove this hypothesis. In the context of cancer therapy, docetaxel can increase the infiltration of cytotox
**[End of Drug Description]**

**Task:** Utilizing the above drug description and considering a predefined list of pathways from the Reactome database (provided below), identify the top 15 pathways most likely to be involved in modulating, translating, synergizing, or antagonizing the efficacy and the metabolism of the drug.

**[Start of Pathways List]**
['ABC-family proteins mediated transport', 'Abacavir ADME', 'Activation of HOX genes during differentiation', 'Adaptive Immune System', 'Amyloid fiber formation', 'Apoptosis', 'Aquaporin-mediated transport', 'Aspirin ADME', 'Atorvastatin ADME', 'Azathioprine ADME', 'BMAL1:CLOCK,NPAS2 activates circadian gene expression', 'Base Excision Repair', 'Binding and Uptake of Ligands by Scavenger Receptors', 'Biological oxidations', 'Cardiac conduction', 'Cardiogenesis', 'Cell Cycle Checkpoints', 'Cell Cycle, Mitotic', 'Cell junction organization', 'Cell surface interactions at the vascular wall', 'Cellular responses to stress', 'Chaperone Mediated Autophagy', 'Chromatin modifying enzymes', 'Chromosome Maintenance', 'Cilium Assembly', 'Ciprofloxacin ADME', 'Class I peroxisomal membrane protein import', 'Collagen formation', 'Cytokine Signaling in Immune system', 'Cytosolic iron-sulfur cluster assembly', 'DNA Damage Bypass', 'DNA Damage Reversal', 'DNA Double-Strand Break Repair', 'DNA Replication Pre-Initiation', 'Deadenylation-dependent mRNA decay', 'Death Receptor Signaling', 'Degradation of the extracellular matrix', 'Digestion', 'Diseases of DNA repair', 'Diseases of Immune System', 'Diseases of cellular response to stress', 'Diseases of hemostasis', 'Diseases of metabolism', 'Diseases of mitotic cell cycle', 'Diseases of programmed cell death', 'Diseases of signal transduction by growth factor receptors and second messengers', 'Diseases of the neuronal system', 'Disorders of Developmental Biology', 'Disorders of transmembrane transporters', 'Dissolution of Fibrin Clot', 'ECM proteoglycans', 'Elastic fibre formation', 'Epigenetic regulation of gene expression', 'Factors involved in megakaryocyte development and platelet production', 'Fanconi Anemia Pathway', 'Fertilization', 'Fibronectin matrix formation', 'Formation of Fibrin Clot (Clotting Cascade)', 'Gastrulation', 'Gene Silencing by RNA', 'Infectious disease', 'Innate Immune System', 'Inositol phosphate metabolism', 'Insertion of tail-anchored proteins into the endoplasmic reticulum membrane', 'Insulin-like Growth Factor-2 mRNA Binding Proteins (IGF2BPs/IMPs/VICKZs) bind RNA', 'Integration of energy metabolism', 'Integrin cell surface interactions', 'Integrin signaling', 'Intestinal absorption', 'Intracellular oxygen transport', 'Intracellular signaling by second messengers', 'Invadopodia formation', 'Ion channel transport', 'Iron uptake and transport', 'Keratinization', 'LGI-ADAM interactions', 'Laminin interactions', 'Late endosomal microautophagy', 'MAPK family signaling cascades', 'MTOR signalling', 'Macroautophagy', 'Maternal to zygotic transition (MZT)', 'Meiosis', 'Membrane Trafficking', 'Metabolism of amino acids and derivatives', 'Metabolism of carbohydrates', 'Metabolism of lipids', 'Metabolism of nitric oxide: NOS3 activation and regulation', 'Metabolism of non-coding RNA', 'Metabolism of nucleotides', 'Metabolism of porphyrins', 'Metabolism of vitamins and cofactors', 'Miscellaneous transport and binding events', 'Mismatch Repair', 'Mitochondrial RNA degradation', 'Mitochondrial biogenesis', 'Mitochondrial calcium ion transport', 'Mitochondrial iron-sulfur cluster biogenesis', 'Mitochondrial protein import', 'Myogenesis', 'NR1D1 (REV-ERBA) represses gene expression', 'Nephrin family interactions', 'Nervous system development', 'Non-integrin membrane-ECM interactions', 'Nonsense-Mediated Decay (NMD)', 'Nucleotide Excision Repair', 'O2/CO2 exchange in erythrocytes', 'Olfactory Signaling Pathway', 'Paracetamol ADME', 'Peptide hormone metabolism', 'Peroxisomal protein import', 'Plasma lipoprotein assembly, remodeling, and clearance', 'Platelet Adhesion to exposed collagen', 'Platelet activation, signaling and aggregation', 'Platelet homeostasis', 'Post-translational protein modification', 'Potassium Channels', 'Prednisone ADME', 'Processing of Capped Intron-Containing Pre-mRNA', 'Processing of Capped Intronless Pre-mRNA', 'Protein folding', 'Protein repair', 'Protein-protein interactions at synapses', 'Pyrophosphate hydrolysis', 'RNA Polymerase I Transcription', 'RNA Polymerase II Transcription', 'RNA Polymerase III Transcription', 'RORA activates gene expression', 'Regulated Necrosis', 'Regulation of Insulin-like Growth Factor (IGF) transport and uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs)', 'Regulation of beta-cell development', 'Regulation of mRNA stability by proteins that bind AU-rich elements', 'Response to metal ions', 'Reversible hydration of carbon dioxide', 'Ribavirin ADME', 'SLC-mediated transmembrane transport', 'Sensory perception of taste', 'Sensory processing of sound', 'Signal regulatory protein family interactions', 'Signaling by Erythropoietin', 'Signaling by GPCR', 'Signaling by Hedgehog', 'Signaling by Hippo', 'Signaling by Leptin', 'Signaling by NODAL', 'Signaling by NOTCH', 'Signaling by Non-Receptor Tyrosine Kinases', 'Signaling by Nuclear Receptors', 'Signaling by Receptor Tyrosine Kinases', 'Signaling by Rho GTPases, Miro GTPases and RHOBTB3', 'Signaling by TGFB family members', 'Signaling by WNT', 'Smooth Muscle Contraction', 'Specification of primordial germ cells', 'Striated Muscle Contraction', 'Surfactant metabolism', 'Synthesis of DNA', 'The citric acid (TCA) cycle and respiratory electron transport', 'Transcription from mitochondrial promoters', 'Transcriptional regulation of granulopoiesis', 'Transcriptional regulation of pluripotent stem cells', 'Transcriptional regulation of testis differentiation', 'Transcriptional regulation of white adipocyte differentiation', 'Translation', 'Transmission across Chemical Synapses', 'Transmission across Electrical Synapses ', 'Visual phototransduction', 'mRNA Capping', 'mRNA Editing', 'rRNA processing', 'tRNA processing']
**[End of Pathways List]**

**Instructions:**
1. **Selection of Pathways:** From the provided list, select 15 pathways that you hypothesize are most relevant to the drug's action based on its known properties and biological interactions.
2. **Rationale for Each Pathway:** For each selected pathway, provide a detailed biological rationale explaining your choice. This should include:
  - The potential role of the pathway in drug action or interaction.
  - How the pathway might modulate, translate, synergize, or antagonize the drug's efficacy.
  - Relevant genes within the pathway that are particularly critical for the drug-pathway interaction.
3. Don't repeat the same pathway more than once.

**Output Format:** Your response should clearly list the selected pathways and genes. Since you're an autoregressive model you should first explain the biological rationale for each choice and the state the choice, structured as follows:

Rationale 1: [Your Rationale]
Pathway 1: [Pathway Name]

Rationale 2: [Your Rationale]
Pathway 2: [Pathway Name]

[...repeat for each selected pathway...] [/INST]

**Answer:**

We than deploy the self consistency procedure and repeat the selection procedure for `self_k` iterations. At the end of each iteration, results from the LLM are collected as a dictionary {'selected_pathway':'rationale'}

In [17]:
dict_list = []

for iter in range(self_k):
    lm = lm + inference(prompt,pathway_number=pathway_number, pathways_list=reactome_pathways,temperature=temperature)
    dict_list.append(dictionary_maker(lm))
    lm.reset()
    gc.collect()
    torch.cuda.empty_cache()

We then use a dedicated function to gather results across iterations and get how many times specific pathways were selected

In [18]:
output_dict = self_consistency(dict_list)
output_dict

{'Cell Cycle, Mitotic': {'count': 2,
  'rationales': [' Docetaxel primarily exerts its effects by binding to and stabilizing microtubules, thereby inhibiting the dynamics of microtubule disassembly and promoting microtubule polymerization. This leads to cell cycle arrest at the G2/M phase, resulting in apoptotic cell death in proliferating cells. The primary target of docetaxel is the beta-tubulin subunit of microtubules, specifically the TUBB protein.',
   " The 'Cell Cycle, Mitotic' pathway is directly related to docetaxel's primary target, the beta-tubulin subunit of microtubules. This pathway is responsible for mitotic cell division, and docetaxel's ability to bind and stabilize microtubules results in mitotic arrest, leading to apoptotic cell death in proliferating cells."]},
 'Cytokine Signaling in Immune system': {'count': 5,
  'rationales': [' Recent studies have shown that docetaxel can activate the cGAS/STING pathway in prostate cancer, subsequently inducing IFN signaling, resulting in lymphocytes infiltration. This immune response facilitates T cell infiltration in a cGAS/STING-dependent manner, providing a combination immunotherapy strategy that would improve the clinical benefits of immunotherapy.',
   ' As docetaxel can activate the cGAS/STING pathway in prostate cancer, leading to lymphocytes infiltration, the Cytokine Signaling in Immune System pathway is essential for understanding its immunomodulatory effects.',
   ' Docetaxel primarily targets the beta-tubulin subunit of microtubules, specifically the TUBB protein. Recent studies have shown that docetaxel can activate the cGAS/STING pathway in prostate cancer, inducing IFN signaling and facilitating T cell infiltration.',
   " The 'Cytokine Signaling in Immune System' pathway is relevant as recent studies have shown that docetaxel can activate the cGAS/STING pathway in prostate cancer, subsequently inducing IFN signaling and lymphocytes infiltration. This immune response facilitates T cell infiltration in a cGAS/STING-dependent manner, providing a combination immunotherapy strategy that improves the clinical benefits of immunotherapy.",
   ' Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. However, it can also increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis. Therefore, pathways involved in T cell costimulation and coinhibition are likely to be modulated by docetaxel.']},
 'Biological oxidations': {'count': 4,
  'rationales': [' Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 system, primarily by CYP3A4. The major metabolic pathways involve hydroxylation of the side chains and the formation of both glucuronide and sulfate conjugates. The primary metabolites include 6α-hydroxy-docetaxel, 6β-hydroxy-docetaxel, and their respective glucuronide and sulfate conjugates. These metabolites are generally less active than the parent compound, docetaxel.',
   " Since docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 system, primarily by CYP3A4, the Biological oxidations and Class I peroxisomal membrane protein import pathways are relevant for the drug's metabolism and clearance.",
   ' Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 system, primarily by CYP3A4. The major metabolic pathways involve hydroxylation of the side chains and the formation of both glucuronide and sulfate conjugates.',
   " Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 system, primarily by CYP3A4. The major metabolic pathways involve hydroxylation of the side chains and the formation of both glucuronide and sulfate conjugates. The primary metabolites include 6α-hydroxy-docetaxel, 6βotedoxane-6α-ol, and their respective glucuronide and sulfate conjugates. These metabolic pathways are likely to be relevant to docetaxel's pharmacokinetics and pharmacodynamics."]},
 'Adaptive Immune System': {'count': 5,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   ' Docetaxel can affect immune system responses, as shown by increasing the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME. The Adaptive Immune System pathway is critical for understanding these effects.',
   ' Docetaxel has been shown to affect immune system responses, affecting cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   " The 'Adaptive Immune System' pathway is essential in the context of docetaxel's use as a component of advanced ovarian cancer management. The adaptive immune system plays a critical role in recognizing and eliminating cancer cells, and its interaction with docetaxel can influence the drug's therapeutic effect.",
   ' Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. However, it can also increase theide of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis. Therefore, pathways involved in the immune response and inflammation are likely to be modulated by docetaxel.']},
 'Innate Immune System': {'count': 5,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   ' Docetaxel can increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells. The Immune System pathway, including both innate and adaptive immunity, helps to understand these complex interactions.',
   ' Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity, but it can also increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis.',
   " The 'Innate Immune System' pathway is relevant as it plays a significant role in the initial response to foreign substances, including drugs. Understanding how docetaxel interacts with this system can help optimize its efficacy and minimize potential side effects.",
   ' Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. However, it can also increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis. Therefore, pathways involved in the regulation of inflammation and immune response are likely to be modulated by docetaxel.']},
 'Diseases of Immune System': {'count': 1,
  'rationales': [' Docetaxel can increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis.']},
 'Intracellular signaling by second messengers': {'count': 1,
  'rationales': [' Docetaxel has been shown to promote HDL biogenesis at low-nanomolar concentrations, far lower than used in chemotherapy. This property may provide new opportunities for the prevention and treatment of atherosclerosis, a disease characterized by the dyslipidemia-induced atherosclerosis.']},
 'Integrin signaling': {'count': 4,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   ' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). The Integrin signaling pathway is essential for understanding cell-cell communication and regulation within the TME.',
   " The 'Integrin signaling' pathway is relevant because docetaxel can affect immune system responses and angiogenesis. This pathway plays a role in the regulation of cell-matrix interactions and cell survival, and docetaxel's interaction with this pathway may influence its therapeutic effect.",
   ' Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. However, it can also increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis. Therefore, pathways involved in T cell migration, extravasation, and tissue infiltration are likely to be modulated by docetaxel.']},
 'Integrin cell surface interactions': {'count': 1,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.']},
 'Membrane Trafficking': {'count': 2,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   ' The biliary route is the primary excretion pathway for both the parent drug and its metabolites, with minimal renal excretion observed.']},
 'Signal regulatory protein family interactions': {'count': 2,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   " The 'Signal regulatory protein family interactions' pathway is relevant because it plays a role in the regulation of immune cell function and inflammation. Docetaxel's interaction with this pathway may influence its therapeutic effect and potential side effects."]},
 'Signaling by Receptor Tyrosine Kinases': {'count': 4,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   ' Docetaxel has been approved in the earlier course of prostate cancer, as it is still castrate sensitive. It has also been approved in the treatment of metastatic urothelial carcinoma and ovarian cancer.',
   " The 'Signaling by Receptor Tyrosine Kinases' pathway is relevant because docetaxel can affect immune system responses and angiogenesis. This pathway plays a role in the regulation of cell proliferation, differentiation, and survival, and docetaxel's interaction with this pathway may influence its therapeutic effect.",
   ' Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. However, it can also increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis. Therefore, pathways involved in T cell costimulation and coinhibition are likely to be modulated by docetaxel.']},
 'Signaling by Non-Receptor Tyrosine Kinases': {'count': 3,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.',
   ' Docetaxel can increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis.',
   ' Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. However, it can also increase the release of immunosuppressive, pro-angiogenic, and metastatic molecules by certain cells such as tumor-associated macrophages (TAMs), cancer-associated fibroblasts (CAFs), and cancer cells, potentially leading to immune evasion, angiogenesis, and metastasis. Therefore, pathways involved in T cellNil regulation, differentiation, and function are likely to be modulated byconnective tissue growth factor (CTGF) docetaxel.']},
 'Signaling by Nuclear Receptors': {'count': 1,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.']},
 'Signaling by GPCR': {'count': 1,
  'rationales': [' Docetaxel can modulate the tumor microenvironment, affecting cancer cells and other cells within the tumor microenvironment (TME). It can affect immune system responses, angiogenesis, and metastasis. For instance, docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity.']},
 'Cell Cycle Checkpoints': {'count': 4,
  'rationales': [" Docetaxel's primary mechanism of action is through microtubule disassembly inhibition, leading to cell cycle arrest and apoptosis. The Cell Cycle Checkpoints and Cell Cycle, Mitotic pathways play crucial roles in this process by controlling the transitions between different phases of the cell cycle.",
   ' The drug docetaxel exerts its antineoplastic effects by binding to and stabilizing microtubules, thereby inhibiting the dynamics of microtubule disassembly and promoting microtubule polymerization.진행하기',
   " The 'Cell Cycle Checkpoints' pathway is crucial for docetaxel's mechanism of action as it interferes with microtubule dynamics, leading to cell cycle arrest at the G2/M phase. This pathway plays a significant role in the regulation of cell division, and docetaxel's ability to modulate this process is key to its anti-cancer effects.",
   ' The drugfif is a semisynthetic antineoplastic agent that binds to and stabilizes microtubules, thereby inhibiting the dynamics of microtubule disassembly and promoting microtubule polymerization. This interference with microtubule dynamics prevents the formation of the mitotic spindle, which is essential for cell division. Consequently, docetaxel induces cell cycle arrest at the G2/M phase, leading to apoptotic cell death in proliferating cells. The primary target of docetaxel is the beta-tubulin subunit of microtubules, specifically the TUBB protein. Therefore, pathways involved in cell cycle regulation and mitotic progression are likely to be affected by docetaxel.']},
 'Binding and Uptake of Ligands by Scavenger Receptors': {'count': 1,
  'rationales': [' Given that the primary excretion pathway for docetaxel and its metabolites is the biliary route, the Bile acid and bile salt transport pathway may be important for understanding its elimination.']},
 'Formation of Fibrin Clot (Clotting Cascade)': {'count': 1,
  'rationales': [" Docetaxel's effects on the tumor microenvironment can influence angiogenesis, a critical process in tumor growth, progression, and metastasis. The Angiogenesis pathway is vital for understanding these effects."]},
 'Cytosolic iron-sulfur cluster assembly': {'count': 3,
  'rationales': [" Docetaxel can induce cell death and enhance chemosensitivity to docetaxel in prostate cancer cells by promoting cuproptosis. Genes such as FDX1, LIAS, and LIPT1 are critical for cuproptosis, making them relevant for docetaxel's mechanism of action.",
   ' Docetaxel undergoes extensive metabolism in the liver by the cytochrome P450 system, primarily by CYP3A4. The major metabolic pathways involve hydroxylation of the side chains and the formation of both glucuronide and sulfate conjugates.',
   " Docetaxel can induce cell death and enhance chemosensitivity to docetaxel in prostate cancer cells by promoting cuproptosis, a copper-induced programmed cell death. This discovery may provide an effective therapeutic option for treating advanced prostate cancer by inhibiting the chemotherapeutic resistance to docetaxel. Therefore, pathways involved in metal ion transport and homeostasis are likely to be relevant to docetaxel's mechanism of action."]},
 'Chromosome Maintenance': {'count': 1,
  'rationales': [' Docetaxel has been shown to promote HDL biogenesis at low-nanomolar concentrations, potentially offering new opportunities for the prevention and treatment of atherosclerosis. The Cholesterol biosynthesis and Regulation of Cholesterol Biosynthesis pathways are relevant for understanding these effects.']},
 'Ciprofloxacin ADME': {'count': 2,
  'rationales': [" Docetaxel can increase the infiltration of cytotoxic CD8+ T lymphocytes and natural killer (NK) cells in the TME, enhancing anti-tumor immunity. Genes such as CD8A, CD56, and granzymes are critical for this process and are thus relevant for docetaxel's mechanism of action.",

In [19]:
len(output_dict)

39

We then list pathways that were selected at least twice for the given drug

In [20]:
#return only pathways with count > 2
for key in output_dict.keys():
    if output_dict[key]['count'] >= 2:
        print(key)

Cell Cycle, Mitotic
Cytokine Signaling in Immune system
Biological oxidations
Adaptive Immune System
Innate Immune System
Integrin signaling
Membrane Trafficking
Signal regulatory protein family interactions
Signaling by Receptor Tyrosine Kinases
Signaling by Non-Receptor Tyrosine Kinases
Cell Cycle Checkpoints
Cytosolic iron-sulfur cluster assembly
Ciprofloxacin ADME
Transcriptional regulation of granulopoiesis
Cell surface interactions at the vascular wall
Macroautophagy
MTOR signalling

Considered than the obtain pathways we can recover the associated genes through the `get_pathway_genes` function

In [19]:
#read the list of pathways together with reactome ids
reactome_pathways_ids = pd.read_csv(data_path/'reactome'/'pathways_l1.csv')

In [24]:
reactome_pathways_ids[reactome_pathways_ids['PathwayName']=='Cell Cycle Checkpoints']

      PathwayID             PathwayName  Layer
16  R-HSA-69620  Cell Cycle Checkpoints      1

In [14]:
get_pathway_genes('R-HSA-109581')

['TRAF2',
 'TRADD',
 'RIPK1',
 'FADD',
 'CASP8',
 'TNFRSF10B',
 'TNFRSF10A',
 'TNFSF10',
 'FASLG',
 'FAS',
 'CD14',
 'TLR4',
 'LY96',
 'TICAM2',
 'TICAM1',
 'ORF71',
 'MC159L',
 'APPL1',
 'DCC',
 'CASP9',
 'CASP3',
 'UNC5B',
 'DAPK2',
 'DAPK3',
 'DAPK1',
 'UNC5A',
 'MAGED1',
 'DIABLO',
 'BAK1',
 'BAX',
 'CYCS',
 'GSDMD',
 'GSDME',
 'APAF1',
 'CASP7',
 'XIAP',
 'CARD8',
 'APIP',
 'AVEN',
 'MAPK3',
 'MAPK1',
 'UACA',
 'CDKN2A',
 'C1QBP',
 'BID',
 'BCL2',
 'BAD',
 'PMAIP1',
 'BBC3',
 'BCL2L11',
 'BMF',
 'BCL2L1',
 'STAT3',
 'MAPK8',
 'DYNLL2',
 'PPP3CC',
 'PPP3R1',
 'YWHAQ',
 'YWHAH',
 'YWHAG',
 'YWHAB',
 'YWHAZ',
 'SFN',
 'YWHAE',
 'AKT3',
 'AKT2',
 'AKT1',
 'DYNLL1',
 'TP53',
 'E2F1',
 'TFDP2',
 'TFDP1',
 'TP63',
 'TP73',
 'TP53BP2',
 'PPP1R13B',
 'NMT1',
 'GZMB',
 'PAK2',
 'ARHGAP10',
 'PSMD8',
 'PSMD6',
 'SEM1',
 'PSMD3',
 'PSMD11',
 'PSMD14',
 'PSMD7',
 'PSMD12',
 'PSMD13',
 'PSMD1',
 'ADRM1',
 'PSMC3',
 'PSMC6',
 'PSMC4',
 'PSMC5',
 'PSMC1',
 'PSMC2',
 'PSMD2',
 'PSMA7',
 'PSMA1',
 'PSMA2',
 'PSMA3',
 'PSMA4',
 'PSMA5',
 'PSMA6',
 'PSMB5',
 'PSMB1',
 'PSMB6',
 'PSMB7',
 'PSMB2',
 'PSMB3',
 'PSMB4',
 'UBC',
 'UBB',
 'UBA52',
 'RPS27A',
 'OMA1',
 'OPA1',
 'DFFA',
 'DFFB',
 'KPNA1',
 'KPNB1',
 'H1-4',
 'H1-5',
 'H1-2',
 'H1-3',
 'H1-1',
 'H1-0',
 'HMGB2',
 'HMGB1',
 'STK26',
 'ACIN1',
 'STK24',
 'BCAP31',
 'BIRC2',
 'BMX',
 'FNTA',
 'PRKCD',
 'CASP6',
 'LMNB1',
 'SATB1',
 'ROCK1',
 'DSG2',
 'OCLN',
 'DSG1',
 'DSP',
 'CDH1',
 'PKP1',
 'CTNNB1',
 'TJP2',
 'DSG3',
 'TJP1',
 'CLSPN',
 'SPTAN1',
 'GAS2',
 'DBNL',
 'GSN',
 'PLEC',
 'VIM',
 'ADD1',
 'MAPT',
 'PTK2',
 'PRKCQ',
 'APC',
 'DNM1L']